<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="favicon" href="assets/images/favicon.png">

	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	
</head>

<body>
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
				<a class="navbar-brand" href="index.html">
					<img src="/zendProject/ZendProject/zendProject/public/assets/images/logo.png" alt="Techro HTML5 template"></a>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav pull-right mainNav">
						
						<li><a href="index.html">Home</a></li>
						<li><a href="profile.html">Profile</a></li>
						<li><a href="courses.html">Courses</a></li>
						<li><a href="http://localhost/zendProject/ZendProject/zendProject/public/MaterialRequest/requestCourse">Ask For course</a></li>
						<li><a href="login.html">Login</a></li> 
						<li><a href="register.html">Register</a></li>
					</ul>
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
		<!-- /.navbar -->

		<header id="head" class="secondary">
			<div class="container">
				<div class="row">
					<div class="col-sm-8">
						<h1>LikeLynda</h1>
					</div>
				</div>
			</div>
		</header>

		<?php echo $this->headScript() ?>
		
		<!-- contents -->
		<?php echo $this->layout()->content; ?>
		<!-- /contents -->

		<footer id="footer">
			<div class="container">
				<div class="social text-center">
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-flickr"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>
				</div>

				<div class="clear"></div>
				<!--CLEAR FLOATS-->
			</div>
			<div class="footer2">
				<div class="container">
					<div class="row">

						<div class="col-md-6 panel">
							<div class="panel-body">
								<p class="simplenav">
									<a href="index.html">Home</a> | 
									<a href="profile.html">Profile</a> |
									<a href="courses.html">Courses</a> |
									<a href="login.html">Login</a> |
									<a href="register.html">Register</a> |
								</p>
							</div>
						</div>

						<div class="col-md-6 panel">
							<div class="panel-body">
								<p class="text-right">
									Copyright &copy; 2014. Template by <a href="http://webthemez.com/" rel="develop">WebThemez.com</a>
								</p>
							</div>
						</div>

					</div>
					<!-- /row of panels -->
				</div>
			</div>
		</footer>

	</body>
	</html>


