<ul class="nav nav-pills nav-stacked  col-xs-4 col-md-2" height="100" >
    <li role="presentation" class="active"><a href="<?php echo $this->url(array('controller'=>'Admin'));?>">manage users</a></li>
    <li role="presentation" class="active"><a href="<?php echo $this->url(array('controller'=>'Course'));?>">manage courses</a></li>
     <li role="presentation" class="active"><a href="<?php echo $this->url(array('controller'=>'Category'));?>">manage categories</a></li>
    <li role="presentation" class="active"><a href="#">manage courses</a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
	<li role="presentation" class="active"><a href="#"></a></li>
	<li role="presentation" class="active"><a href="#">manage courses</a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
	<li role="presentation" class="active"><a href="#"></a></li>
</ul>

<a href="<?php echo $this->url(array('controller'=>'category',
	 'action'=>'add'));?>">Add</a>
<table border="1px">
<tr>
	 <th>Username</th>
	 <th>Action</th>
	 <th>&nbsp;</th>
</tr>

<?php foreach($this->categories as $category) : ?>
<tr>
 <td><?php echo $this->escape($category->name);?></td>
 <td>
 <a href="<?php echo $this->url(array('controller'=>'category',
	 'action'=>'edit', 'id'=>$category->id));?>">Edit</a>
	 <a href="<?php echo $this->url(array('controller'=>'category',
	 'action'=>'delete', 'id'=>$category->id));?>">Delete</a>
 </td>
</tr>
<?php endforeach; ?>
</table>