<div class="col-md-6">
	<ul class="nav nav-tabs nav-justified">
		<a href="<?php echo $this->url(array('controller'=>'category',
			 'action'=>'add'));?>">Add New Category</a>
	 </ul>
	<table class="table table-bordered table-condensed table-hover">
		<tr>
			 <th>Name</th>
			 <th colspan="3">Actions</th>
		</tr>
		<?php foreach($this->categories as $category){ ?>
			<tr>
				<td><?php echo $this->escape($category->name);?></td>			
				 	<td>
				 	 <a class ="label label-primary" href="<?php echo $this->url(array('controller'=>'category',
					 'action'=>'edit', 'id'=>$category->id));?>">Edit</a>
					 </td>
					 <td>
					 <a class="label label-danger" href="<?php echo $this->url(array('controller'=>'category',
					 'action'=>'delete', 'id'=>$category->id));?>">Delete</a>
					 </td>
					 <td>
					 <a href="<?php echo $this->url(array('controller'=>'category',
					 'action'=>'courses', 'id'=>$category->id));?>">courses</a>
				 	</td>
			</tr>
		<?php }; ?>
	</table>
</div>