<ul class="nav nav-pills nav-stacked  col-xs-4 col-md-2" height="100" >
    <li role="presentation" class="active"><a href="<?php echo $this->url(array('controller'=>'Admin'));?>">manage users</a></li>
    <li role="presentation" class="active"><a href="<?php echo $this->url(array('controller'=>'Course'));?>">manage courses</a></li>
     <li role="presentation" class="active"><a href="<?php echo $this->url(array('controller'=>'Category'));?>">manage categories</a></li>
    <li role="presentation" class="active"><a href="#">manage courses</a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
	<li role="presentation" class="active"><a href="#"></a></li>
	<li role="presentation" class="active"><a href="#">manage courses</a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
    <li role="presentation" class="active"><a href="#"></a></li>
	<li role="presentation" class="active"><a href="#"></a></li>
</ul>