<div class="col-md-6">
    <ul class="nav nav-tabs nav-justified">
        <li><a href="<?php echo $this->url(array('controller'=>'course',
         'action'=>'add'));?>">Add new Course</a></li>
    </ul>
<table class="table table-bordered table-condensed table-hover">
    <tr>
         <th>Course name</th>
         <th>Category</th>
         <th colspan="2">Action</th>
    </tr>
    <?php foreach($this->course as $course) : ?>
    <tr>
         <td><a href="<?php echo $this->url(array('controller'=>'course', 'action'=>'edit', 'id'=>$course->id));?>"><?php echo $this->escape($course->name);?></a>
         </td>
         <td><?php echo $this->escape($course->category_id);?></a>
         </td>
         <td>
             <a class="label label-primary" href="<?php echo $this->url(array('controller'=>'course',
             'action'=>'edit', 'id'=>$course->id));?>">Edit</a>
             <a class="label label-danger" href="<?php echo $this->url(array('controller'=>'course',
             'action'=>'delete', 'id'=>$course->id));?>">Delete</a>
         </td>
    </tr>
    <?php endforeach; ?>
</table>
</div>