<?php 

if($this->my_material){
		echo "<h3 style='margin-left:20;color:blue'>".$this->my_material['name']."</h3>";
		echo "<h3 style='margin-left:20;'>".$this->my_material['file_path']."</h3>";
		echo "<img src='http://localhost/zendProject/ZendProject/zendProject/public/upload/".$this->my_material['file_path']."'/>";

		echo "<h3 style='margin-left:20;'>".$this->my_material['type']."</h3>";
	}

?>