<?php
	$this->title = "Materials";
	$this->headTitle($this->title);
?>
<div class="col-md-8">
	<ul class="nav nav-tabs nav-justified">
		<p><a href="<?php echo $this->url(array('controller'=>'Material',
		 'action'=>'add'));?>">Add New Material</a></p>
	 </ul>
	<table class="table table-bordered table-condensed table-hover">
		<tr>
			 <th>name</th>
			 <th>file path</th>
			 <th>type</th>
			 <th>is downloadable</th>
			 <th>is hidden</th>
			 <th>downloads</th>
			 <th>course id</th>
			 <th>user id</th>
			 <th>Actions</th>
		</tr>
		<?php foreach($this->materials as $material) : ?>
			<tr>
				 <td><?php echo $this->escape($material->name);?></td>
				 <td><?php echo $this->escape($material->file_path);?></td>
				 <td><?php echo $this->escape($material->type);?></td>
				 <td><?php if($material->is_downloadable == 0){ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Material','action'=>'download','id'=>$material->id));?>">
							<?php echo $this->escape($material->is_downloadable);   }
						else{ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Material','action'=>'undownload','id'=>$material->id));?>">
							<?php echo $this->escape($material->is_downloadable); }?>
						 </a>
				</td>
				<td>		 
				 <?php if($material->is_hidden == 0){ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Material','action'=>'hide','id'=>$material->id));?>">
							<?php echo $this->escape($material->is_hidden);   }
						else{ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Material','action'=>'show','id'=>$material->id));?>">
							<?php echo $this->escape($material->is_hidden); }?>
						 </a>
				 </td>
				 <td><?php echo $this->escape($material->downloads_count);?></td>
				 <td><?php echo $this->escape($material->course_id);?></td>
				 <td><?php echo $this->escape($material->user_id);?></td>
				<td>
				<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Material',
					 'action'=>'edit', 'id'=>$material->id));?>">Edit </a>
					 <a class = "label label-danger" href="<?php echo $this->url(array('controller'=>'Material',
					 'action'=>'delete', 'id'=>$material->id));?>"> Delete</a>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>