<div class="col-md-6">
   		<ul class="nav nav-tabs nav-justified">
			<a href="<?php echo $this->url(array('controller'=>'Admin',
			 'action'=>'add'));?>">Add</a><br />
		</ul>
    <table class="table table-bordered table-condensed table-hover">

		<tr>
			 <th>Username</th>
			 <th>Email</th>
			 <th>Gender</th>
			 <th>Country</th>
			 <th>Admin</th>
			 <th>Banned</th>
			 <th>Actions</th>
		</tr>
		<?php foreach($this->user as $user) : ?>
			<tr>
			  	<td><?php echo $this->escape($user->username);?></td>
				<td><?php echo $this->escape($user->email);?></td> 				    
				<!-- <td><?php echo $this->escape($user->password);?></td> -->
	            <!-- <td><?php echo $this->escape($user->image);?></td> -->
			    <!-- <td><?php echo $this->escape($user->signature);?></td> -->
				<td><?php echo $this->escape($user->gender);?></td>
				<td><?php echo $this->escape($user->country);?></td>
				<td>
						<?php if($user->is_admin == 0){ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Admin','action'=>'upgrade','id'=>$user->id));?>">
							<?php echo $this->escape($user->is_admin);   }
						else{ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Admin','action'=>'degrade','id'=>$user->id));?>">
							<?php echo $this->escape($user->is_admin); }?>
						 </a>
				</td>
				<td>
					 <?php if($user->is_banned == 0){ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Admin','action'=>'ban','id'=>$user->id));?>">
							<?php echo $this->escape($user->is_banned);   }
						else{ ?>
							<a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Admin','action'=>'allow','id'=>$user->id));?>">
							<?php echo $this->escape($user->is_banned); }?>
						 </a>
				</td>
					

				<td><a class = "label label-primary" href="<?php echo $this->url(array('controller'=>'Admin','action'=>'edit', 'id'=>$user->id));?>">Edit </a>

				<a class = "label label-danger" href="<?php echo $this->url(array('controller'=>'Admin','action'=>'delete', 'id'=>$user->id));?>">Delete</a></td>
			</tr>
		<?php endforeach; ?>
	</table>
	<br/>
</div>